name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@9885a4f9af674ba472de91fb3c0cb033ecb32b7e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Update major tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RE: '[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
          LATEST_VERSION: ${{ steps.bump-version.outputs.tag }}
        run: |
          TAG="$(echo ${LATEST_VERSION:1} | sed -e "s#$RE#\1#")"
          git tag -d $TAG || true
          git tag $TAG                   
          commit=$(git rev-parse HEAD)

          URL=https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs          

          curl \
            -X DELETE \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            $URL/tags/$TAG

          curl \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            $URL \
            -d '{"ref":"'"refs/tags/$TAG"'", "sha":"'"$commit"'"}'
